Start
ArtCode-Kazan/SeisReaderLibrary pull request #1
Opened 2022-12-08 14:35 UTC by fotuka

2022-12-08 14:37 UTC, fotuka commented on BinReader.cs
> +            //this.__unique_file_name = this.__create_unique_file_name()
Убрать комментарий

2022-12-29 08:10 UTC, MikkoArtik requested changes
Отличная работа сделана! Увидел свою версию библиотеки на Python. Перевод на C# считаю получился удачным. Есть некоторые вопросы и правки, но они больше косметические.
Жду ответов на вопросы и правки

2022-12-29 08:10 UTC, MikkoArtik commented on BinReader.cs
> +        }
какое красивое решение!

2022-12-29 08:10 UTC, MikkoArtik commented on BinReader.cs
> +        //return '{}.{}'.format(uuid.uuid4().hex, self.file_extension)
убери мусор

2022-12-29 08:10 UTC, MikkoArtik commented on BinReader.cs
> +        public dynamic GetComponentSignal(string componentName = "Y")
Убери значение агрумента по умолчанию. Здесь не нужно этого

2022-12-29 08:10 UTC, MikkoArtik commented on BinReader.cs
> +            //signal_array = np.ndarray(signal_size, buffer = mm, dtype = np.int32, offset = offset_size, strides = strides_size).copy()
убери мусор

2022-12-29 08:10 UTC, MikkoArtik commented on BinReader.cs
> +        }
здорово! Похоже, ты смог реализовать быстрое чтение, как в библиотеке Python. А можно здесь функцию снабдить комментариями? Хотелось бы посмотреть детальнее, что тут происходит

2022-12-29 09:08 UTC, fotuka commented on BinReader.cs
> +        public DateTime __ReadDatetimeStop;
я видел, чтобы _ и в c# писали

2022-12-29 10:10 UTC, fotuka commented on BinReader.cs
> +                signalLength = signalLength - (signalLength % ResampleParameter);
👍

2022-12-29 11:09 UTC, fotuka commented on BinReader.cs
> +        public DateTime __ReadDatetimeStop;
Если переименовывать в Name вместо __Name, то методы с get'ерами придется тоже переименовывать, потому что у них название Name, константы тоже пишутся с большой буквы.  оставил просто _Name

2022-12-29 11:24 UTC, fotuka commented on BinReader.cs
> +                }
Если _ReadDateTimeStop не заполнен, то заполняется

2022-12-29 11:25 UTC, fotuka commented on BinReader.cs
> +                }
А если заполнен, то не меняется, возвращается как есть

2022-12-29 11:25 UTC, fotuka commented on BinReader.cs
> +                }
Если _ReadDateTimeStart не заполнен, то заполняется

2022-12-29 11:25 UTC, fotuka commented on BinReader.cs
> +                }
А если заполнен, то не меняется, возвращается как есть

2022-12-29 11:26 UTC, fotuka commented on BinReader.cs
> +        }
Благодарю, правда наверное можно упростить еще лучше сделать, написать ResampleSignal[i] = sum сразу

2022-12-29 11:56 UTC, fotuka commented on BinReader.cs
> +        }
Написал, смотри

2022-12-29 12:41 UTC, MikkoArtik requested changes
Стало намного яснее. Жду правки

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +                string hoursFmt = Convert.ToString(hours).PadLeft(2, '0');
то, что и просил. Супер

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +    public class Constants
класс констант подними выше всех. Сразу после namespace, чтоб не искать их в дебрях кода

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +                        {Constants.SigmaFmt, Constants.SigmaExtension}
превосходно!

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
>                  var indexes = new Dictionary<string, string>()
почему переменная называется indexes? тут нет индексов

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +        public readonly string _Path;
почему _ оставил?

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
>              stream.Read(data, 0, 336);
а зачем прочитывать 336 байт?

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
>              string stroke = "";
неудачные имена переменных - легко спутать с именами типов. Лучше так:
- valueInt16, valueInt32 и т.д

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
>              stream.Read(data, 0, 336);
а stream зачем? вижу, что дальше используется только MemoryStream

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
>              var memoryStream = new MemoryStream(data, 0, 336);
почему здесь тоже 336?

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +                string extension = Path.GetExtension(path).Replace(".", "");
лучше все-таки так:
https://learn.microsoft.com/ru-ru/dotnet/api/system.string.substring?view=net-7.0

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +                }
> Если _ReadDateTimeStop не заполнен, то заполняется

можно по умолчанию сразу его выставить, чтобы было this.__ReadDatetimeStop = DatetimeStop. Тогда проверка не нужна будет

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +                }
> Если _ReadDateTimeStart не заполнен, то заполняется
> 

см. выше

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
>                  }
в комментариях написал

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +                    this._ReadDatetimeStop = DatetimeStop;
в комментариях написал

2022-12-29 12:41 UTC, MikkoArtik commented on BinReader.cs
> +            Int32[] intArray = new int[byteArrayClip.Length / 4];
откуда 4?

2022-12-29 12:48 UTC, fotuka commented on BinReader.cs
>              stream.Read(data, 0, 336);
Потому что это длина шапки

2022-12-29 12:49 UTC, fotuka commented on BinReader.cs
> +                }
Это прописано в конструкторе

2022-12-29 12:55 UTC, fotuka commented on BinReader.cs
>              var memoryStream = new MemoryStream(data, 0, 336);
Потому что это длина шапки

2022-12-29 12:55 UTC, fotuka commented on BinReader.cs
> +            Int32[] intArray = new int[byteArrayClip.Length / 4];
потому что одно значение Int32 занимает 4 байта

2022-12-29 12:57 UTC, fotuka commented on BinReader.cs
> +        public readonly string _Path;
Если переименовывать в Name вместо __Name, то методы с get'ерами придется тоже переименовывать, потому что у них название Name, константы тоже пишутся с большой буквы. оставил просто _Name

2022-12-29 12:59 UTC, fotuka commented on BinReader.cs
>              stream.Read(data, 0, 336);
тут из stream записывается в data массив 336 байт начиная с 0 байта

2022-12-29 13:02 UTC, fotuka commented on BinReader.cs
> +                    this._ReadDatetimeStop = DatetimeStop;
ответил в комментарии

2022-12-29 13:42 UTC, fotuka commented
Сделал так, чтобы считывалось 8 байт с нужной позиции, это соответствует самому большому числу (double или int64).
Если будет 2 байта, то он просто считает первые два байта, остальные 6 получается лишние останутся
Можно сделать чтобы ровно считывал, но придется тогда переписать все на case ы, я кстати так или иначе хотел переписывать этот метод, уж по дурацки слишком эта куча if else смотрится

2022-12-29 13:59 UTC, MikkoArtik requested changes
Практически все. Остались моменты с пояснением некоторых участков кода

2022-12-29 13:59 UTC, MikkoArtik commented on BinReader.cs
> +        public readonly string _Path;
> Если переименовывать в Name вместо __Name, то методы с get'ерами придется тоже переименовывать, потому что у них название Name, константы тоже пишутся с большой буквы. оставил просто _Name

принято. нет вопросов

2022-12-29 13:59 UTC, MikkoArtik commented on BinReader.cs
>              stream.Read(data, 0, 336);
> Потому что это длина шапки

а надо ли ее сразу всю читать? думаю, нет

2022-12-29 13:59 UTC, MikkoArtik commented on BinReader.cs
>              stream.Read(data, 0, 336);
> тут из stream записывается в data массив 336 байт начиная с 0 байта

ощущение, что что-то здесь лишнее, промежуточное, без чего можно обойтись. Прикрепи ссылки, откуда брал как читать бинарные данные

2022-12-29 14:02 UTC, fotuka commented on BinReader.cs
>              stream.Read(data, 0, 336);
Смотри последний комментарий в общей теме pull request

2022-12-29 14:03 UTC, fotuka commented on BinReader.cs
>              stream.Read(data, 0, 336);
если честно, не помню, смотрел как у тебя написано в python и что не было в c# гуглил как сделать, сборная солянка

2022-12-29 14:13 UTC, MikkoArtik requested changes
ключевые моменты пока не решены

2022-12-29 14:13 UTC, MikkoArtik commented on BinReader.cs
>              stream.Read(data, 0, 336);
> если честно, не помню, смотрел как у тебя написано в python и что не было в c# гуглил как сделать, сборная солянка

надо разобраться будет

2022-12-29 14:13 UTC, MikkoArtik commented on BinReader.cs
> +            Int32[] intArray = new int[byteArrayClip.Length / 4];
а можно же получить это число так: https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/operators/sizeof
исправь все четверки на sizeof. Так все вопросы исчезают
константы в коде - плохая практика

2022-12-29 20:43 UTC, fotuka commented
Разобрался, написал по новой можно сказать метод BinaryRead, осталось переписать на такой же манер GetComponentSignal. А также разобраться с DateTimeStart и DateTimeStop (есть некоторые вопросы к создателю библиотеки seiscore на python)

2022-12-30 06:55 UTC, MikkoArtik requested changes
Один метод хорошо пофиксил. Остался еще один - чтение сигнала

2022-12-30 06:55 UTC, MikkoArtik commented on BinReader.cs
> +        {
Вот теперь все прозрачно и понятно. И не нужны комментарии. Супер!

2022-12-30 06:55 UTC, MikkoArtik commented on BinReader.cs
>          public dynamic GetComponentSignal(string componentName)
Этот метод надо еще оптимизировать

2023-01-09 08:30 UTC, MikkoArtik requested changes
Остались мелкие правки. сегодня можно будет завершить

2023-01-09 08:30 UTC, MikkoArtik commented on BinReader.cs
> +                if (extension == Constants.Baikal7Extension | extension == Constants.Baikal8Extension | extension == Constants.SigmaExtension)
может лучше сделать через HashSet?
https://www.geeksforgeeks.org/c-sharp-check-if-a-hashset-contains-the-specified-element/

2023-01-09 08:30 UTC, MikkoArtik commented on BinReader.cs
>                  var componentOffset = new Dictionary<string, int>()
почему переменная/ носит такое имя? тут нет же сдвига, только индексы компонент

2023-01-09 08:30 UTC, MikkoArtik commented on BinReader.cs
> +                columnIndex += 3;
нужно тройку заменить на количество компонент, чтобы не было константы в коде

2023-01-09 08:30 UTC, MikkoArtik commented on BinReader.cs
> +                        {RecordType.Substring(2,1), 2}
может заполнение сделать через цикл?

2023-01-09 10:05 UTC, fotuka commented on BinReader.cs
> +                if (extension == Constants.Baikal7Extension | extension == Constants.Baikal8Extension | extension == Constants.SigmaExtension)
Предлагаю компромисс - воспользоваться существующим словарем 
Constants.BinaryFileFormats.ContainsValue(extension)

2023-01-09 10:58 UTC, MikkoArtik requested changes
Жду исправления ошибок

2023-01-09 10:58 UTC, MikkoArtik commented on BinReader.cs
> +                var componentIndex = new Dictionary<string, int>();
множественное число должно быть

2023-01-09 10:58 UTC, MikkoArtik commented on BinReader.cs
> +                }
все верно

2023-01-09 13:03 UTC, MikkoArtik requested changes
Отлично! Остались мелкие правки

2023-01-09 13:03 UTC, MikkoArtik commented on BinReader.cs
> +                return _FileHeader.frequency;
почему нет this?

2023-01-09 13:03 UTC, MikkoArtik commented on BinReader.cs
> +                return _FileHeader.channelCount;
тоже нет this

2023-01-09 13:03 UTC, MikkoArtik commented on BinReader.cs
> +                return Math.Round(_FileHeader.latitude, 6);
тоже нет this

2023-01-09 13:48 UTC, MikkoArtik reviewed
Видимых ошибок нет. Нужно протестировать в простом консольном приложении в ручном режиме

2023-02-20 10:41 UTC, merged