Dev tests
ArtCode-Kazan/SeisReaderLibrary pull request #3
Opened 2023-01-30 13:04 UTC by fotuka

2023-01-30 13:30 UTC, MikkoArtik requested changes
Сделать декомпозицию для интерфейса BinaryFile - внутри встречаются поля (геттеры/сеттеры), которые можно объединить в один класс. Например, longitude+latitude, datetime interval и прочее. Конечно, тестировать удобно стало, а вот понимать код стало намного труднее.

2023-01-30 13:30 UTC, MikkoArtik commented on BinReader.cs
> +    public interface IBinarySeismicFile
тут нужня явно декомпозиция на более мелкие блоки

2023-01-30 13:30 UTC, MikkoArtik commented on BinReader.cs
> +        double Latitude { get; }
можно объединить в блок Coordinate

2023-01-30 13:30 UTC, MikkoArtik commented on BinReader.cs
> +        DateTime ReadDatetimeStop { get; set; }
объединить два метода в один, чтобы проставлять интервал для чтения за один раз

2023-01-30 13:30 UTC, MikkoArtik commented on BinReader.cs
> +        FileHeader ReadSigmaHeader(string path);
напрашивается вынос в отдельный класс

2023-01-30 13:30 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTest.cs
> +            var mock = new Mock<BinaryFileInfo>("", "", 0, new DateTime(), new DateTime(), 0, 0) { CallBase = true };
именование аргументов  реализуемо?

2023-02-08 07:18 UTC, fotuka commented on BinaryReaderLibraryTest/UnitTest.cs
> +            var mock = new Mock<BinaryFileInfo>("", "", 0, new DateTime(), new DateTime(), 0, 0) { CallBase = true };
нет, когда Mock создается он не хочет принимать именованные

2023-02-08 07:18 UTC, fotuka commented
https://github.com/ArtCode-Kazan/SeisReaderLibrary/pull/3#discussion_r1099743644

2023-02-08 12:43 UTC, fotuka commented on BinReader.cs
> +    public interface IBinarySeismicFile
нет не нужна

2023-02-08 12:45 UTC, fotuka reviewed
Посмотреть как реализовать запуск тестов перед сборкой

2023-02-09 05:54 UTC, MikkoArtik requested changes
Небольшие ошибки в нейминге. А так можно приступать к покрытию тестами. Молодец!

2023-02-09 05:54 UTC, MikkoArtik commented on BinReader.cs
> +            this._ReadDatetimeStop = this.DateTimeInterval.stop;
поля ReadDatetime объедини в DatetimeInterval

2023-02-09 05:54 UTC, MikkoArtik commented on BinReader.cs
> +        public virtual DateTimeInterval DateTimeInterval
переименовать DateTimeInterval в RecordDateTimeInterval

2023-02-16 10:11 UTC, MikkoArtik reviewed
Часть ревью сделал. Объемный код. Остальную часть буду смотреть после правок

2023-02-16 10:11 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
> +        [DataRow("txt", null)]
почему не константы из библиотеки?

2023-02-16 10:11 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
> +        public void testHeaderMemorySize(int chcount)
имя паеременной некорректно - исправить

2023-02-16 10:11 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
> +            string path = Environment.CurrentDirectory + filename;
константы

2023-02-16 10:11 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
> +                    { writer.Write(BitConverter.GetBytes((Int32)2)); ; }
нужно, учесть, что каналов 3

2023-02-16 17:56 UTC, MikkoArtik requested changes
Впечатлен проделанной работой. Виден прогресс. Как будто этой мой код)
Есть небольшие правки. Думаю, это предпоследнее ревью. Так держать!

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>          [DataRow(60000, 0, 0, -40591, 45678, true)]
хороший набор кейсов собрал!

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>          [DataRow(4234, 434, 9)]
краевые случаи охватил. здорово

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
> +            int expected = sec * 1000 - startMoment;
1000 - это, предполагаю, частота. вынеси в переменную

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
> +            expected = expected - (expected % 4);
4 - это параметр ресемплирования. заведи лучше отдельную переменную, иначе непонятно, что это сразу

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>          [DataRow(100, -100, false)]
даже такой случай предусмотрел)

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>          [DataRow(new int[10] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 2, new int[5] { 2, 4, 6, 8, 10 })]
сделай кейс, когда длина сигнала не делится нацело на параметр ресемплирования.
и нет кейса еще, когда ресемплированное значение получается без округления

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>              File.Delete(path);
давай уборку делать после теста, в самом конце

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>              var random = new Random();
в этом тесте записывается только одна компонента во временный файл?

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
> +            int expectedArrayAvg = 0;
тут же находится сумма элементов. Пусть носит имя суммы

2023-02-16 17:56 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>              File.Delete(path);
уборку в конец теста

2023-02-16 20:39 UTC, fotuka commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>          [DataRow(new int[10] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 2, new int[5] { 2, 4, 6, 8, 10 })]
по поводу ресемплированного значения без округления не понял про что ты.

2023-02-16 20:39 UTC, fotuka commented
https://github.com/ArtCode-Kazan/SeisReaderLibrary/pull/3#discussion_r1108825723 тут немного непонял

2023-02-16 20:41 UTC, fotuka commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>              File.Delete(path);
точно, работает. почему то думал, что после ассерта код дальше не пойдет

2023-02-16 20:43 UTC, fotuka commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>              var random = new Random();
да. после write идет seek на 8 байт(2 числа оставшихся)

2023-02-16 20:44 UTC, fotuka commented
https://github.com/ArtCode-Kazan/SeisReaderLibrary/pull/3#discussion_r1108834965 ответил.

2023-02-17 13:27 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>          [DataRow(new int[10] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 }, 2, new int[5] { 2, 4, 6, 8, 10 })]
> по поводу ресемплированного значения без округления не понял про что ты.

Например, дан сигнал: `signal = [1, 3, 4, 8, 10, 12]` и параметр ресемплинга `resampling_parameter=2`.
В этом случае новые значения получаются без остатка от деления: `(1 +3) / 2 = 2, (4 + 8) / 2 = 6` и т.д. Этот кей имел в виду

2023-02-20 08:12 UTC, MikkoArtik requested changes
Жду правок

2023-02-20 08:12 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
>              double btw = Convert.ToDouble(discreteCount) / freq;
неясные имена переменных

2023-02-20 08:12 UTC, MikkoArtik commented on BinaryReaderLibraryTest/UnitTestBinReader.cs
> +            mockbsf.Object._FileHeader = mockfh.Object;
сделать понятнее имена переменных

2023-02-20 10:31 UTC, merged