naming
ArtCode-Kazan/SeisReaderLibrary pull request #6
Opened 2023-06-01 11:08 UTC by fotuka

2023-06-01 14:37 UTC, MikkoArtik requested changes
Основные замечения:
- нейминг переменных
- посмотреть более подходящее исключение

2023-06-01 14:37 UTC, MikkoArtik commented on BinReader.cs
>              {
#Ask
Точно ли нет типа OSError? Это более подходящее исключение

2023-06-01 14:37 UTC, MikkoArtik commented on BinaryReaderLibraryTest/BinaryReaderLibraryTest.cs
> +            NameInfo binaryNameInfo = mock.Object.GetBinaryNameInfo();
binaryNameInfo - переменные имеют некорректные имена

2023-06-02 04:06 UTC, fotuka commented on BinReader.cs
>              {
FileFormatException

2024-04-25 08:02 UTC, MikkoArtik approved these changes

2024-04-25 08:02 UTC, merged